server.port: 9000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: ADMIN-SERVICE
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**

        - id: HR-SERVICE
          uri: lb://HR-SERVICE
          predicates:
            - Path=/hr/**

        - id: TNL-SERVICE
          uri: lb://TNL-SERVICE
          predicates:
            - Path=/tnl/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost